sharathchandramg/react-formo

- packages/react-web-formo/package-lock.json
- packages/react-web-formo/package.json
- packages/react-web-formo/src/fields/dateTimePicker/index.js
- packages/react-web-formo/src/fields/dateTimePicker/style.css
- packages/react-web-formo/src/fields/lookup/index.js
- packages/react-web-formo/src/fields/lookup/pagination.css
- packages/react-web-formo/src/fields/lookup/pagination.js
- packages/react-web-formo/src/fields/lookup/style.css
- packages/react-web-formo/src/fields/picker/index.js
- packages/react-web-formo/src/fields/statusPicker/index.js
- packages/react-web-formo/src/fields/textInput/index.js
- packages/react-web-formo/src/index.js
- packages/react-web-formo/src/utils/helper.js
- packages/sample-app/public/index.html
Add Lookup field and editable condition for inputs
> Lookup field

- packages/react-web-formo/src/fields/dateTimePicker/index.js
- packages/sample-app/package.json
> Remove default date, if no date is selected

- packages/react-web-formo/src/utils/helper.js
Add default value for yesterday date
> Add default value for yesterday date

- packages/react-web-formo/src/fields/dateTimePicker/index.js
- packages/react-web-formo/src/utils/helper.js
Refactor date field to send epoch format
> Hotfix date

- packages/react-web-formo/src/fields/textInput/index.js
Add check to disable auto increment number
> Add check for disable auto incr number

- packages/react-web-formo/package.json
- packages/react-web-formo/src/fields/textInput/index.js
- packages/react-web-formo/src/index.js
- packages/react-web-formo/src/utils/helper.js
Added calculated expression field
> Added calculated expression field

- packages/react-web-formo/src/fields/Select/index.js
- packages/react-web-formo/src/fields/Select/style.css
- packages/react-web-formo/src/index.js
- packages/react-web-formo/src/utils/helper.js
- packages/react-web-formo/src/utils/validators.js
> Story 1012 Added Multi select field

- packages/react-web-formo/src/fields/textInput/index.js
Fixed number field is not showing 0 value
> Fix not showing 0 in number field

- packages/react-web-formo/src/fields/image/index.js
- packages/react-web-formo/src/fields/image/style.css
- packages/react-web-formo/src/fields/location/index.js
- packages/react-web-formo/src/index.js
- packages/react-web-formo/src/utils/helper.js
> Added image data type

- packages/react-web-formo/src/fields/image/index.js
Fix second image is not render on update form
> Fix second image is not render on update form

- packages/react-web-formo/src/index.js
Fix re rendering on update form
> Fix re rendering on update form

- packages/react-web-formo/src/fields/document/index.js
- packages/react-web-formo/src/fields/document/style.css
- packages/react-web-formo/src/index.js
> Added document data type

- packages/react-web-formo/src/utils/helper.js
Fix required validation for document
> Fix required validation for document

- packages/react-web-formo/src/fields/cascadingDropdown/index.js
- packages/react-web-formo/src/fields/cascadingDropdown/searchableDropDown.js
- packages/react-web-formo/src/fields/cascadingDropdown/styles.css
- packages/react-web-formo/src/index.js
- packages/react-web-formo/src/utils/helper.js
Added cascading dropdown field
> Added cascading dropdown field

- packages/react-web-formo/package.json
- packages/react-web-formo/src/index.js
- packages/react-web-formo/src/utils/helper.js
Update inline calculation for number fields
> Update inline calculation for number fields

- packages/react-web-formo/src/fields/Select/index.js
- packages/react-web-formo/src/fields/Select/style.css
- packages/react-web-formo/src/fields/cascadingDropdown/styles.css
- packages/react-web-formo/src/fields/checklist/style.css
- packages/react-web-formo/src/fields/customDataView/style.css
- packages/react-web-formo/src/fields/dateTimePicker/index.js
- packages/react-web-formo/src/fields/document/style.css
- packages/react-web-formo/src/fields/image/style.css
- packages/react-web-formo/src/fields/location/index.js
- packages/react-web-formo/src/fields/longtext/index.js
- packages/react-web-formo/src/fields/lookup/style.css
- packages/react-web-formo/src/fields/picker/index.js
- packages/react-web-formo/src/fields/picker/style.css
- packages/react-web-formo/src/fields/statusPicker/index.js
- packages/react-web-formo/src/fields/textInput/index.js
- packages/react-web-formo/src/fields/userDirectory/style.css
Update picker and multi select to show options in inline
Update fields label and value styles
> Update picker and multi select to show options in inline and Update fields label and value styles

- packages/react-web-formo/src/fields/picker/style.css
- packages/react-web-formo/src/index.js
Fix undefined key in data payload
> Fix undefined key in data payload

- packages/react-web-formo/package.json
> Upgrade version to 0.0.52

- packages/react-web-formo/src/index.js
- packages/react-web-formo/src/utils/helper.js
Fix signature data is not showing in update form
> Fix signature data is not showing in update form

- packages/react-web-formo/package.json
> Upgrade version to 0.0.55

- packages/react-web-formo/package.json
Fix time showing 12hr for 24 hr format
> Upgrade version to 0.0.57

- packages/react-web-formo/src/fields/textInput/index.js
- packages/react-web-formo/src/fields/textInput/style.css
- packages/react-web-formo/src/index.js
- Fixed calculated number field is not calculating if value is 0
- Remove scroll of number input field to change value
> Fix calc number if value is 0 and on scroll of input field

- packages/react-web-formo/package.json
Fixed calc number field and scroll on number input
> Fixed calc number field and scroll on number input

- packages/react-web-formo/package.json
Fix calc num fields to calculate on form open
> Fix calc num fields to calculate on form open

- packages/react-web-formo/package.json
Remove editable check on create form
> Remove editable check on create form

- packages/react-web-formo/src/fields/cascadingDropdown/index.js
- packages/react-web-formo/src/fields/location/index.js
- packages/react-web-formo/src/fields/textInput/index.js
- packages/react-web-formo/src/fields/textInput/style.css
- packages/react-web-formo/src/index.js
- packages/react-web-formo/src/utils/helper.js
Add the check conditions for allowDecimal, allowNegative, maxCondition and minCondition
> Number field

- packages/react-web-formo/src/fields/cascadingDropdown/searchableDropDown.js
- packages/react-web-formo/src/fields/cascadingDropdown/styles.css
- packages/react-web-formo/src/fields/textInput/index.js
- packages/react-web-formo/src/index.js
- packages/react-web-formo/src/utils/helper.js
- Show no data found if options not available in cascading
- Add no validation for calc number fields
> Show no data found if options not available in cascading

- packages/react-web-formo/package.json
- packages/react-web-formo/src/fields/textInput/index.js
- packages/react-web-formo/src/fields/userDirectory/index.js
- packages/react-web-formo/src/index.js
- packages/react-web-formo/src/utils/helper.js
Update expression to calculate for field names
> Update expression to calculate for field names

- packages/react-web-formo/package.json
- packages/react-web-formo/src/fields/dateTimePicker/index.js
- packages/react-web-formo/src/fields/lookup/index.js
- packages/react-web-formo/src/index.js
- packages/react-web-formo/src/utils/helper.js
> Add new mode in date field

- packages/react-web-formo/src/index.js
Update user field with filteration
> Update user field with filteration
